import { Check, Clock3, LockKeyhole, Play, Target } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { LearningPathTopic } from '../../types'
import { ProgressBar } from '../ui/ProgressBar'

export function LearningPathNode({ topic }: { topic: LearningPathTopic }) {
  const locked = topic.status === 'locked'
  return <div className={`relative rounded-2xl border p-5 ${locked || topic.status === 'not-started' ? 'border-slate-200 bg-slate-50' : topic.status === 'current' ? 'border-indigo-200 bg-indigo-50/50 shadow-sm' : 'border-slate-200 bg-white'}`}><div className="flex items-start gap-4"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full ${topic.status === 'completed' ? 'bg-emerald-100 text-emerald-700' : topic.status === 'current' ? 'bg-indigo-600 text-white' : locked || topic.status === 'not-started' ? 'bg-slate-200 text-slate-500' : 'bg-indigo-50 text-indigo-600'}`} aria-label={`${topic.status} topic`}>{topic.status === 'completed' ? <Check className="h-5 w-5" /> : locked ? <LockKeyhole className="h-5 w-5" /> : topic.status === 'current' ? <Target className="h-5 w-5" /> : <span className="text-sm font-bold">{topic.id.slice(0, 1).toUpperCase()}</span>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-900">{topic.name}</h3><span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${topic.status === 'completed' ? 'bg-emerald-50 text-emerald-700' : topic.status === 'current' ? 'bg-indigo-100 text-indigo-700' : 'bg-slate-100 text-slate-600'}`}>{topic.status}</span></div><p className="mt-2 text-sm leading-6 text-slate-500">{topic.description}</p><div className="mt-4 flex flex-wrap gap-3 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" />{topic.estimatedMinutes} min</span><span>{topic.difficulty}</span>{topic.prerequisites.length > 0 && <span>Prerequisite: {topic.prerequisites.join(', ')}</span>}</div>{topic.progress > 0 && <div className="mt-4 max-w-sm"><ProgressBar value={topic.progress} label="Progress" /></div>}<Link to={`/learn/topic/${topic.id}`} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-indigo-700">{locked ? 'Preview Topic' : topic.status === 'completed' ? 'Review topic' : 'Learn Topic'} <Play className="h-3.5 w-3.5" /></Link></div></div></div>
}
