import { ArrowRight, CheckCircle2, Target, XCircle } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Card } from '../ui/Card'

export function QuizResult({ score, correct, total, difficultyPath, topic, onPracticeAgain }: { score: number; correct: number; total: number; difficultyPath: string[]; topic: string; onPracticeAgain: () => void }) {
  const weak = score < 60
  const strong = score >= 80
  return <div className="space-y-5"><Card className="bg-slate-900 text-center text-white"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-indigo-500"><Target className="h-7 w-7" /></div><h1 className="mt-5 text-3xl font-bold">Practice Complete 🎉</h1><p className="mt-2 text-slate-300">{topic}</p><p className="mt-7 text-6xl font-bold text-indigo-300">{score}%</p><p className="mt-2 text-slate-300">{correct} / {total} correct</p></Card><div className="grid gap-4 sm:grid-cols-3"><Card><CheckCircle2 className="h-5 w-5 text-emerald-600" /><p className="mt-4 text-sm text-slate-500">Correct answers</p><p className="mt-1 text-2xl font-bold text-slate-950">{correct}</p></Card><Card><XCircle className="h-5 w-5 text-rose-600" /><p className="mt-4 text-sm text-slate-500">Incorrect answers</p><p className="mt-1 text-2xl font-bold text-slate-950">{total - correct}</p></Card><Card><Target className="h-5 w-5 text-indigo-600" /><p className="mt-4 text-sm text-slate-500">Accuracy</p><p className="mt-1 text-2xl font-bold text-slate-950">{score}%</p></Card></div><Card><h2 className="font-semibold text-slate-900">Difficulty progression</h2><div className="mt-4 flex flex-wrap items-center gap-2">{difficultyPath.map((level, index) => <span key={`${level}-${index}`} className="inline-flex items-center gap-2"><span className="rounded-full bg-indigo-50 px-3 py-1.5 text-xs font-semibold capitalize text-indigo-700">{level}</span>{index < difficultyPath.length - 1 && <ArrowRight className="h-4 w-4 text-slate-400" />}</span>)}</div></Card><Card className={weak ? 'border-red-100 bg-red-50/70' : strong ? 'border-emerald-100 bg-emerald-50/70' : 'border-indigo-100 bg-indigo-50/70'}><h2 className="font-semibold text-slate-900">{weak ? 'Weak topic detected' : strong ? 'Strong topic' : 'Keep building this skill'}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{weak ? `${topic} is currently below 60%. Review the fundamentals and try an easier practice set.` : strong ? `You are performing well in ${topic}. Try advanced questions next.` : `Practise similar questions to make ${topic} more consistent.`}</p><button type="button" onClick={onPracticeAgain} className="mt-4 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700">{weak ? 'Practice easier questions' : strong ? 'Try advanced questions' : 'Practice similar questions'}</button><Link to="/learn" className="ml-3 inline-flex items-center gap-1 text-sm font-semibold text-indigo-700">Review explanation <ArrowRight className="h-4 w-4" /></Link></Card></div>
}
