import { BarChart3, BookOpen, Flame, Target, Trophy } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { ActivityList } from '../components/dashboard/ActivityCard'
import { RecommendationCard } from '../components/dashboard/RecommendationCard'
import { RevisionList } from '../components/dashboard/RevisionCard'
import { StatCard } from '../components/dashboard/StatCard'
import { WeakTopicCard } from '../components/dashboard/WeakTopicCard'
import { Card } from '../components/ui/Card'
import { ProgressBar } from '../components/ui/ProgressBar'
import { SectionHeader } from '../components/ui/SectionHeader'
import { dashboardPreview, demoProfile } from '../data/demoData'
import { getDemoLearningPath, getDemoRecommendation } from '../services/learningPathService'
import { calculateAnalyticsOverview, generateInsights } from '../services/analyticsService'
import { getLearningState } from '../services/learningState'
import { getDueRevisions } from '../services/revisionService'

export function DashboardPage() {
  const [params] = useSearchParams()
  const mode = params.get('mode') === 'demo' ? 'demo' : 'normal'
  const isDemo = mode === 'demo'
  const state = getLearningState(mode)
  const overview = calculateAnalyticsOverview(mode)
  const path = getDemoLearningPath('Computer Networks', mode)
  const progress = isDemo ? dashboardPreview.progress : overview.overallProgress
  const accuracy = isDemo ? dashboardPreview.quizAccuracy : overview.accuracy
  const completed = isDemo ? dashboardPreview.topicsCompleted : overview.completedTopics
  const practiced = isDemo ? dashboardPreview.questionsPracticed : overview.questionsAttempted
  const streak = isDemo ? dashboardPreview.studyStreak : overview.studyStreak
  const current = path.topics.find((item) => item.status === 'current') ?? path.topics.find((item) => item.status === 'not-started')
  const recommendation = getDemoRecommendation(path.topics)
  const insights = generateInsights(mode)
  const due = getDueRevisions(mode)
  const weakTopics = isDemo ? dashboardPreview.weakTopics : state.progress.filter((item) => item.status === 'Weak').map((item) => ({ name: path.topics.find((topic) => topic.id === item.topicId)?.name ?? item.topicId, accuracy: item.accuracyPercentage }))
  const strongTopics = isDemo ? dashboardPreview.strongTopics : state.progress.filter((item) => item.status === 'Strong').map((item) => ({ name: path.topics.find((topic) => topic.id === item.topicId)?.name ?? item.topicId, accuracy: item.accuracyPercentage }))
  return <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:py-10">
    <header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-indigo-600">Tuesday, September 11</p>{isDemo && <span className="rounded-full border border-indigo-100 bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-indigo-700">Demo Mode — Sample learning data</span>}</div><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">{isDemo ? 'Good evening 👋' : 'Welcome to LearnMate AI'}</h1><p className="mt-2 text-slate-500">{isDemo ? `Ready to continue learning, ${demoProfile.name}?` : 'Start your learning journey.'}</p>{isDemo && <p className="mt-3 max-w-xl text-xs leading-5 text-slate-500">Sample learning data is being used to demonstrate LearnMate AI&apos;s personalized learning features.</p>}</div><Link to={`/analytics${isDemo ? '?mode=demo' : ''}`} className="inline-flex items-center gap-2 text-sm font-semibold text-indigo-600 hover:text-indigo-700">View learning insights <BarChart3 className="h-4 w-4" /></Link></header>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Progress" value={`${progress}%`} detail={isDemo ? dashboardPreview.currentTopic : progress ? 'Computer Networks learning path' : 'No topic started yet'} icon={BookOpen} accent="indigo" /><StatCard label="Quiz accuracy" value={isDemo || overview.questionsAttempted ? `${accuracy}%` : 'No attempts yet'} detail={isDemo ? 'Sample quiz performance' : overview.questionsAttempted ? 'Based on submitted quiz answers' : 'Complete a quiz to see accuracy'} icon={Trophy} accent="emerald" /><StatCard label="Study streak" value={`${streak} days`} detail={isDemo ? 'Sample study streak' : state.studySessions ? 'Based on recorded study sessions' : 'No study sessions yet'} icon={Flame} accent="amber" /><StatCard label="Questions practiced" value={String(practiced)} detail={isDemo ? 'Sample practice activity' : practiced ? 'Submitted quiz questions' : 'No quiz activity yet'} icon={Target} accent="rose" /></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-[1fr_.8fr]"><Card><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-indigo-600">Learning Overview</p><h2 className="mt-1 text-xl font-bold text-slate-950">Your momentum at a glance</h2></div><Link to={`/analytics${isDemo ? '?mode=demo' : ''}`} className="text-sm font-semibold text-indigo-600">View Full Analytics</Link></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><span>Progress<br /><strong>{progress}%</strong></span><span>Accuracy<br /><strong>{isDemo || overview.questionsAttempted ? `${accuracy}%` : 'No data yet'}</strong></span><span>Topics<br /><strong>{completed}</strong></span><span>Streak<br /><strong>{streak} days</strong></span></div></Card><Card><p className="text-sm font-semibold text-indigo-600">Learning Insight</p><p className="mt-2 font-semibold text-slate-900">{insights[0]?.text ?? 'Start learning to generate personalized insights.'}</p></Card></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><Card><p className="text-sm font-semibold text-indigo-600">Continue Learning</p><h2 className="mt-2 text-xl font-bold text-slate-950">{current ? current.name : 'No topic started yet'}</h2><p className="mt-2 text-sm text-slate-500">{current ? (isDemo ? 'Computer Networks · 48% progress' : state.attempts.length ? `${state.attempts.length} quiz attempt${state.attempts.length === 1 ? '' : 's'} recorded` : 'Choose a topic to begin learning.') : 'Choose a topic to begin learning.'}</p>{current && <Link to={`/learn?topic=${encodeURIComponent(current.name)}`} className="mt-5 inline-flex text-sm font-semibold text-indigo-700">Start Learning</Link>}</Card>{isDemo ? <RecommendationCard title={recommendation.title} reason={recommendation.reason} actionLabel={`${recommendation.action} now`} to={`/practice?topic=${encodeURIComponent(current?.name ?? 'Subnetting')}&difficulty=beginner`} assistantTo={`/assistant?subject=Computer%20Networks&topic=Subnetting&level=beginner&learningStyle=analogy&accuracy=48`} /> : state.progress.some((item) => item.status === 'Weak') ? <RecommendationCard title="Practice Subnetting" reason="Your recorded quiz performance shows this topic needs targeted practice." actionLabel="Practice now" to="/practice?topic=Subnetting&difficulty=beginner" assistantTo="/assistant?subject=Computer%20Networks&topic=Subnetting&level=beginner&learningStyle=step-by-step" /> : <Card><p className="text-sm font-semibold text-indigo-600">Recommended Next Step</p><h2 className="mt-2 text-xl font-bold text-slate-950">Choose a topic to begin learning.</h2><Link to="/learn/path" className="mt-5 inline-flex text-sm font-semibold text-indigo-700">Explore Learning Path</Link></Card>}</section>
    <section className="mt-10"><SectionHeader eyebrow="Your focus" title={isDemo ? 'Make your next session count.' : 'Your learning focus'} description={isDemo ? 'These are the areas that deserve attention based on sample learning activity.' : 'Weak topics will appear here after you complete a quiz.'} /></section>
    <section className="mt-5 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-semibold text-slate-900">Weak topics</h2>{weakTopics.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{weakTopics.map((topic) => <WeakTopicCard key={topic.name} {...topic} />)}</div> : <p className="mt-4 text-sm text-slate-500">None yet.</p>}</Card><Card><h2 className="font-semibold text-slate-900">Strong topics</h2>{strongTopics.length ? <div className="mt-5 space-y-4">{strongTopics.map((topic) => <div key={topic.name}><div className="flex justify-between text-sm"><span className="font-medium text-slate-700">{topic.name}</span><span className="font-semibold text-emerald-600">{topic.accuracy}%</span></div><div className="mt-2"><ProgressBar value={topic.accuracy} tone="emerald" /></div></div>)}</div> : <p className="mt-4 text-sm text-slate-500">None yet.</p>}</Card></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-semibold text-slate-900">Recent activity</h2>{state.activity.length ? <ActivityList items={state.activity} /> : <p className="mt-4 text-sm text-slate-500">No recent activity yet.</p>}</Card><Card><h2 className="font-semibold text-slate-900">Revision due</h2>{due.length ? <RevisionList items={due} /> : <p className="mt-4 text-sm text-slate-500">None.</p>}</Card></section>
  </div>
}
