import { ArrowRight, BarChart3, BrainCircuit, CheckCircle2, ChevronRight, ClipboardCheck, Compass, LineChart, RefreshCw, ShieldCheck, Sparkles, Target, Waypoints } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Navbar } from '../components/layout/Navbar'
import { Card } from '../components/ui/Card'
import { dashboardPreview } from '../data/demoData'

const steps = [
  { number: '01', icon: Compass, title: 'Choose', text: 'Choose a subject and topic.' },
  { number: '02', icon: BrainCircuit, title: 'Understand', text: 'AI explains the concept according to your knowledge level.' },
  { number: '03', icon: ClipboardCheck, title: 'Practice', text: 'Take adaptive quizzes and receive explanations for mistakes.' },
  { number: '04', icon: Target, title: 'Improve', text: 'LearnMate identifies weak topics and recommends what to study next.' },
]

const features = [
  { icon: BrainCircuit, title: 'AI Concept Explainer', text: 'Clear, level-aware explanations with analogies, examples, and common mistakes.' },
  { icon: ClipboardCheck, title: 'Adaptive Quiz', text: 'Practice at a difficulty that responds to your recent performance.' },
  { icon: Target, title: 'Weak Topic Detection', text: 'See exactly which concepts need more attention based on your answers.' },
  { icon: Waypoints, title: 'Personalized Learning Path', text: 'Follow a focused roadmap with prerequisites and a clear next step.' },
  { icon: RefreshCw, title: 'Smart Revision', text: 'Return to important topics at a practical, lightweight rhythm.' },
  { icon: BarChart3, title: 'Learning Analytics', text: 'Turn study activity into progress insights you can act on.' },
]

export function LandingPage() {
  return <div className="page-shell soft-grid min-h-screen">
    <Navbar />
    <main>
      <section className="mx-auto grid max-w-7xl items-center gap-14 px-5 pb-20 pt-14 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:pb-28 lg:pt-24">
        <div><p className="mb-6 inline-flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-1.5 text-sm font-semibold text-indigo-700"><Sparkles className="h-4 w-4" />AI-assisted learning, built around your progress</p><h1 className="max-w-3xl text-5xl font-bold leading-[1.06] tracking-[-0.04em] text-slate-950 sm:text-6xl lg:text-7xl">Your AI-powered <span className="text-indigo-600">personalized</span> learning companion.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">Learn difficult concepts in a way that matches your level, practice with adaptive quizzes, identify your weak areas, and know exactly what to study next.</p><div className="mt-8 flex flex-wrap gap-3">        <Link to="/onboarding" className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Start Learning <ArrowRight className="h-4 w-4" /></Link>        <Link to="/dashboard?mode=demo" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-700 transition-colors hover:border-indigo-200 hover:text-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Explore Demo <ChevronRight className="h-4 w-4" /></Link></div><p className="mt-6 text-sm font-medium text-slate-500">AI-assisted learning <span className="mx-2 text-slate-300">•</span> Personalized practice <span className="mx-2 text-slate-300">•</span> Progress insights</p></div>
        <div className="relative"><div className="absolute -inset-5 rounded-[2.5rem] bg-indigo-100/50 blur-2xl" /><Card className="relative overflow-hidden border-indigo-100 p-0 shadow-xl shadow-indigo-100/50"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-red-400" /><span className="h-2.5 w-2.5 rounded-full bg-amber-400" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-400" /></div><span className="text-xs font-semibold text-slate-400">learnmate.app/dashboard</span></div><div className="bg-slate-50/70 p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-indigo-600">Student dashboard</p><h2 className="mt-2 text-xl font-bold text-slate-900">Good evening 👋</h2><p className="mt-1 text-sm text-slate-500">Ready to continue learning?</p></div><span className="rounded-full bg-indigo-100 px-2.5 py-1 text-xs font-bold text-indigo-700">{dashboardPreview.progress}% progress</span></div><div className="mt-6 rounded-2xl bg-slate-900 p-5 text-white"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-indigo-300">Continue learning</p><h3 className="mt-2 font-semibold">{dashboardPreview.currentTopic}</h3></div><span className="rounded-full bg-white/10 px-2 py-1 text-xs">In progress</span></div><div className="mt-5 h-2 rounded-full bg-white/10"><div className="h-2 w-[72%] rounded-full bg-indigo-400" /></div><div className="mt-2 flex justify-between text-xs text-slate-400"><span>72% complete</span><span>18 topics completed</span></div></div><div className="mt-4 grid grid-cols-3 gap-3">{[['Accuracy', '82%'], ['Streak', '7 days'], ['Practised', '146']].map(([label, value]) => <div key={label} className="rounded-xl bg-white p-3 shadow-sm"><p className="text-[11px] text-slate-400">{label}</p><p className="mt-1 font-bold text-slate-900">{value}</p></div>)}</div></div></Card></div>
      </section>
      <section className="border-y border-slate-200/70 bg-white/70"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-indigo-600">The learning gap</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Learning shouldn&apos;t be one-size-fits-all.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[['Passive Learning', 'Students read notes repeatedly without knowing what they actually understand.'], ['Hidden Weaknesses', 'Students may complete chapters without identifying the concepts they struggle with.'], ['Random Practice', 'Students often practise questions that do not match their actual learning needs.']].map(([title, text]) => <Card key={title}><p className="text-lg font-semibold text-slate-900">{title}</p><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p></Card>)}</div><div className="mt-10 flex items-center gap-3 rounded-2xl bg-indigo-600 px-5 py-4 text-white shadow-lg shadow-indigo-100"><CheckCircle2 className="h-5 w-5 shrink-0" /><p className="font-semibold">LearnMate AI changes this with a complete loop from understanding to measurable improvement.</p></div></div></section>
      <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-indigo-600">How it works</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">A better next step, every time.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-4">{steps.map(({ number, icon: Icon, title, text }) => <div key={number} className="relative rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="text-sm font-bold text-indigo-600">{number}</span><Icon className="mt-8 h-6 w-6 text-slate-900" /><h3 className="mt-5 font-semibold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></section>
      <section id="features" className="bg-slate-50/80"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-indigo-600">Built for real study sessions</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Everything you need to make practice count.</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <Card key={title} className="transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md"><span className="inline-flex rounded-xl bg-indigo-50 p-3 text-indigo-600"><Icon className="h-5 w-5" /></span><h3 className="mt-5 font-semibold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></Card>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="overflow-hidden rounded-3xl bg-slate-900 p-8 text-white sm:p-12"><div className="grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-indigo-300">The difference</p><h2 className="mt-4 text-3xl font-bold sm:text-4xl">More than an AI chatbot.</h2><p className="mt-5 leading-7 text-slate-300">LearnMate uses quiz performance and learning activity to personalize the student&apos;s next step—not just generate another answer.</p></div><div className="grid gap-3 sm:grid-cols-5">{[['LEARN', BrainCircuit], ['PRACTICE', ClipboardCheck], ['ANALYZE', LineChart], ['PERSONALIZE', Sparkles], ['REVISE', RefreshCw]].map(([label, Icon], index) => <div key={label as string} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 sm:block sm:text-center"><Icon className="h-5 w-5 text-indigo-300 sm:mx-auto" /><p className="mt-0 text-xs font-bold tracking-wider text-white sm:mt-3">{label as string}</p>{index < 4 && <ArrowRight className="ml-auto h-4 w-4 text-slate-500 sm:hidden" />}</div>)}</div></div></div></section>
      <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="rounded-3xl border border-indigo-100 bg-indigo-50/70 p-8 sm:flex sm:items-center sm:justify-between sm:p-10"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-indigo-600">Ready to learn with intent?</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">Start with one difficult concept.</h2></div>      <Link to="/onboarding" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:mt-0">Start Learning <ArrowRight className="h-4 w-4" /></Link></div></section>
      <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-8"><p className="font-semibold text-slate-900">LearnMate AI</p><p>AI-assisted learning content should be verified with trusted sources.</p><Link to="/responsible-ai" className="font-semibold text-indigo-600">Responsible AI <ShieldCheck className="inline h-4 w-4" /></Link></div></footer>
    </main>
  </div>
}
