import { ArrowRight, UserRound } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'

export function OnboardingPage() {
  const navigate = useNavigate()
  const [name, setName] = useState('Aarav')
  return <div className="mx-auto max-w-3xl px-5 py-10 sm:px-8 lg:py-16"><div className="mb-8"><span className="inline-flex rounded-xl bg-indigo-50 p-3 text-indigo-600"><UserRound className="h-6 w-6" /></span><h1 className="mt-5 text-4xl font-bold tracking-tight text-slate-950">Build your learning profile</h1><p className="mt-3 text-lg leading-8 text-slate-600">Tell us how you learn best so LearnMate can shape a focused demo journey.</p></div><Card><form className="space-y-5" onSubmit={(event) => { event.preventDefault(); navigate('/dashboard') }}><label className="block text-sm font-semibold text-slate-800">Name<input value={name} onChange={(event) => setName(event.target.value)} required minLength={2} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /></label><label className="block text-sm font-semibold text-slate-800">Education level<select className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"><option>College student</option><option>Competitive-exam learner</option><option>Professional learner</option></select></label><label className="block text-sm font-semibold text-slate-800">Learning goal<select className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"><option>Prepare for technical interviews</option><option>Strengthen academic foundations</option><option>Build practical skills</option></select></label><label className="block text-sm font-semibold text-slate-800">Current knowledge level<select className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><Button type="submit" className="w-full justify-center py-3">Continue to dashboard <ArrowRight className="ml-2 h-4 w-4" /></Button></form><p className="mt-4 text-xs leading-5 text-slate-500">LearnMate only asks for learning preferences needed to personalize the experience. This demo does not persist profile data.</p></Card></div>
}
